//! Translate an s3cmd `.s3cfg` (and the rs5cmd `~/.rs5cmd` dotfile, which shares
//! the parser) into rs5cmd connection/transfer settings, to ease migration from
//! s3cmd. Consumed by the `--s3cfg` flag and the `import-s3cfg` subcommand in
//! [`crate::command`].
//!
//! s3cmd keeps *everything* — credentials, endpoint, TLS, proxy, transfer tuning
//! — in one INI file, whereas rs5cmd uses the AWS credential chain plus CLI
//! flags. [`translate_s3cfg`] maps the recognized `.s3cfg` keys onto a
//! [`Translated`] set of overrides; options rs5cmd cannot honor are surfaced as
//! [`Translated::warnings`] rather than silently dropped.

use std::collections::HashMap;

/// Connection/transfer overrides distilled from a config file. Every field is
/// optional (`None`/`false` == "not specified"); the caller applies them onto
/// `GlobalOpts` only where the user left the corresponding flag unset, so an
/// explicit CLI flag always wins.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct Translated {
    pub access_key: Option<String>,
    pub secret_key: Option<String>,
    pub session_token: Option<String>,
    pub endpoint_url: Option<String>,
    pub addressing_style: Option<String>,
    pub region: Option<String>,
    pub no_verify_ssl: bool,
    pub ca_certs_file: Option<String>,
    pub proxy: Option<String>,
    pub retry_count: Option<u32>,
    pub limitrate: Option<u64>,
    pub request_payer: Option<String>,
    /// Notes about options that could not be translated (e.g. SigV2).
    pub warnings: Vec<String>,
}

impl Translated {
    /// Serializes the non-secret connection settings as an rs5cmd-native INI
    /// (the `~/.rs5cmd` dotfile read back by [`from_rs5cmd`]). Credentials are
    /// deliberately omitted — they belong in `~/.aws/credentials`.
    pub fn to_rs5cmd_ini(&self) -> String {
        let mut out = String::from("# rs5cmd config (generated by `import-s3cfg`)\n[rs5cmd]\n");
        let mut kv = |k: &str, v: &str| {
            out.push_str(k);
            out.push_str(" = ");
            out.push_str(v);
            out.push('\n');
        };
        if let Some(v) = &self.endpoint_url {
            kv("endpoint_url", v);
        }
        if let Some(v) = &self.region {
            kv("region", v);
        }
        if let Some(v) = &self.addressing_style {
            kv("addressing_style", v);
        }
        if self.no_verify_ssl {
            kv("no_verify_ssl", "true");
        }
        if let Some(v) = &self.ca_certs_file {
            kv("ca_certs_file", v);
        }
        if let Some(v) = &self.proxy {
            kv("proxy", v);
        }
        if let Some(v) = &self.retry_count {
            kv("retry_count", &v.to_string());
        }
        if let Some(v) = &self.limitrate {
            kv("limitrate", &v.to_string());
        }
        if let Some(v) = &self.request_payer {
            kv("request_payer", v);
        }
        out
    }
}

/// Parses a minimal INI: `[section]` headers (ignored — all keys merge into one
/// map, matching s3cmd's single `[default]` section), `key = value` pairs, and
/// `#`/`;` comment lines. Keys are lowercased; later duplicates win.
pub fn parse_ini(text: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with(';') {
            continue;
        }
        if line.starts_with('[') {
            continue; // section header — sections are not distinguished
        }
        if let Some((k, v)) = line.split_once('=') {
            map.insert(k.trim().to_ascii_lowercase(), v.trim().to_string());
        }
    }
    map
}

/// Parses a byte count/rate accepting a bare integer (bytes) or a human size
/// such as `1MB`/`1MiB`/`1.5g`. Used for both `--limitrate` and the `.s3cfg`
/// `limitrate` key (which s3cmd records as plain bytes/second).
pub fn parse_byte_rate(s: &str) -> Result<u64, String> {
    let s = s.trim();
    if let Ok(n) = s.parse::<u64>() {
        return Ok(n);
    }
    s.parse::<bytesize::ByteSize>()
        .map(|b| b.as_u64())
        .map_err(|e| format!("invalid byte rate {s:?}: {e}"))
}

/// Interprets an s3cmd-style boolean (`True`/`False`/`1`/`0`/`yes`/`no`).
fn parse_bool(s: &str) -> Option<bool> {
    match s.trim().to_ascii_lowercase().as_str() {
        "true" | "1" | "yes" | "on" => Some(true),
        "false" | "0" | "no" | "off" => Some(false),
        _ => None,
    }
}

fn nonempty(map: &HashMap<String, String>, key: &str) -> Option<String> {
    map.get(key)
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

/// Maps s3cmd `bucket_location`/`region` values to AWS region codes. s3cmd uses
/// the legacy location constraints `US` and `EU`; everything else passes through.
fn normalize_region(loc: &str) -> String {
    match loc.trim() {
        "US" | "us" => "us-east-1".to_string(),
        "EU" | "eu" => "eu-west-1".to_string(),
        other => other.to_string(),
    }
}

/// Translates a parsed `.s3cfg` map into rs5cmd overrides.
pub fn translate_s3cfg(map: &HashMap<String, String>) -> Translated {
    let mut t = Translated {
        access_key: nonempty(map, "access_key"),
        secret_key: nonempty(map, "secret_key"),
        session_token: nonempty(map, "access_token"),
        ca_certs_file: nonempty(map, "ca_certs_file"),
        ..Default::default()
    };

    // Endpoint: host_base + use_https (s3cmd defaults use_https to true).
    if let Some(host) = nonempty(map, "host_base") {
        let host = host.trim_end_matches('/');
        let lower = host.to_ascii_lowercase();
        if lower.starts_with("http://") || lower.starts_with("https://") {
            t.endpoint_url = Some(host.to_string());
        } else {
            let https = map
                .get("use_https")
                .and_then(|v| parse_bool(v))
                .unwrap_or(true);
            let scheme = if https { "https" } else { "http" };
            t.endpoint_url = Some(format!("{scheme}://{host}"));
        }
    }

    // Addressing style from the host_bucket template: a leading `%(bucket)s`
    // means virtual-host (`bucket.host`); anything else is path-style.
    if let Some(hb) = nonempty(map, "host_bucket") {
        t.addressing_style = Some(if hb.trim_start().starts_with("%(bucket)s") {
            "virtual".to_string()
        } else {
            "path".to_string()
        });
    }

    // Region: prefer an explicit `region`, else the legacy `bucket_location`.
    if let Some(r) = nonempty(map, "region").or_else(|| nonempty(map, "bucket_location")) {
        t.region = Some(normalize_region(&r));
    }

    // TLS verification: either knob being false disables verification.
    let cert_off = map.get("check_ssl_certificate").and_then(|v| parse_bool(v)) == Some(false);
    let host_off = map.get("check_ssl_hostname").and_then(|v| parse_bool(v)) == Some(false);
    if cert_off || host_off {
        t.no_verify_ssl = true;
    }

    // Proxy: s3cmd stores host + port separately; rs5cmd wants a URL.
    if let Some(ph) = nonempty(map, "proxy_host") {
        let lower = ph.to_ascii_lowercase();
        if lower.starts_with("http://")
            || lower.starts_with("https://")
            || lower.starts_with("socks5")
        {
            t.proxy = Some(ph);
        } else {
            let port = map
                .get("proxy_port")
                .and_then(|p| p.trim().parse::<u16>().ok())
                .unwrap_or(3128);
            t.proxy = Some(format!("http://{ph}:{port}"));
        }
    }

    if let Some(n) = map
        .get("max_retries")
        .and_then(|v| v.trim().parse::<u32>().ok())
    {
        t.retry_count = Some(n);
    }

    if let Some(raw) = nonempty(map, "limitrate") {
        match parse_byte_rate(&raw) {
            Ok(n) if n > 0 => t.limitrate = Some(n),
            Ok(_) => {} // 0 == unlimited in s3cmd
            Err(e) => t.warnings.push(format!("ignoring limitrate: {e}")),
        }
    }

    if map.get("requester_pays").and_then(|v| parse_bool(v)) == Some(true) {
        t.request_payer = Some("requester".to_string());
    }

    // Options rs5cmd cannot honor — surface rather than silently drop.
    if map.get("signature_v2").and_then(|v| parse_bool(v)) == Some(true) {
        t.warnings.push(
            "signature_v2 is not supported (rs5cmd signs with SigV4 only); ignoring".to_string(),
        );
    }
    if nonempty(map, "storage_class").is_some() {
        t.warnings.push(
            "storage_class is not applied globally; pass --storage-class per command".to_string(),
        );
    }
    let sse = map
        .get("server_side_encryption")
        .and_then(|v| parse_bool(v))
        == Some(true);
    if sse || nonempty(map, "kms_key").is_some() {
        t.warnings.push(
            "server-side encryption is not applied globally; pass --sse/--sse-kms-key-id per command"
                .to_string(),
        );
    }
    if map.get("encrypt").and_then(|v| parse_bool(v)) == Some(true) {
        t.warnings
            .push("client-side GPG encryption (encrypt) is not supported; ignoring".to_string());
    }

    t
}

/// Reads back the rs5cmd-native `~/.rs5cmd` dotfile (the format written by
/// [`Translated::to_rs5cmd_ini`]). Native keys map straight onto the fields.
pub fn from_rs5cmd(map: &HashMap<String, String>) -> Translated {
    Translated {
        access_key: nonempty(map, "access_key"),
        secret_key: nonempty(map, "secret_key"),
        session_token: nonempty(map, "session_token"),
        endpoint_url: nonempty(map, "endpoint_url"),
        addressing_style: nonempty(map, "addressing_style"),
        region: nonempty(map, "region"),
        no_verify_ssl: map
            .get("no_verify_ssl")
            .and_then(|v| parse_bool(v))
            .unwrap_or(false),
        ca_certs_file: nonempty(map, "ca_certs_file"),
        proxy: nonempty(map, "proxy"),
        retry_count: map
            .get("retry_count")
            .and_then(|v| v.trim().parse::<u32>().ok()),
        limitrate: nonempty(map, "limitrate").and_then(|v| parse_byte_rate(&v).ok()),
        request_payer: nonempty(map, "request_payer"),
        warnings: Vec::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_ini_ignoring_comments_and_sections() {
        let text = "\
# a comment
[default]
access_key = AKIA
secret_key =  s3cr3t
; another comment
use_https = True
";
        let m = parse_ini(text);
        assert_eq!(m.get("access_key").unwrap(), "AKIA");
        assert_eq!(m.get("secret_key").unwrap(), "s3cr3t");
        assert_eq!(m.get("use_https").unwrap(), "True");
        assert!(!m.contains_key("[default]"));
    }

    #[test]
    fn translates_path_style_https_endpoint() {
        // OSiRIS/Ceph-RGW style config.
        let m = parse_ini(
            "[default]\n\
             access_key = AK\n\
             secret_key = SK\n\
             host_base = rgw.osris.org\n\
             host_bucket = rgw.osris.org/%(bucket)s\n\
             use_https = True\n\
             signature_v2 = True\n",
        );
        let t = translate_s3cfg(&m);
        assert_eq!(t.access_key.as_deref(), Some("AK"));
        assert_eq!(t.secret_key.as_deref(), Some("SK"));
        assert_eq!(t.endpoint_url.as_deref(), Some("https://rgw.osris.org"));
        assert_eq!(t.addressing_style.as_deref(), Some("path"));
        assert!(t.warnings.iter().any(|w| w.contains("signature_v2")));
    }

    #[test]
    fn translates_virtual_host_and_http() {
        let m = parse_ini(
            "host_base = http://localhost:9000\n\
             host_bucket = %(bucket)s.localhost:9000\n\
             check_ssl_certificate = False\n",
        );
        let t = translate_s3cfg(&m);
        // Scheme already present → used verbatim.
        assert_eq!(t.endpoint_url.as_deref(), Some("http://localhost:9000"));
        assert_eq!(t.addressing_style.as_deref(), Some("virtual"));
        assert!(t.no_verify_ssl);
    }

    #[test]
    fn translates_proxy_region_retries_and_rate() {
        let m = parse_ini(
            "proxy_host = proxy.local\n\
             proxy_port = 8080\n\
             bucket_location = EU\n\
             max_retries = 3\n\
             limitrate = 1048576\n\
             requester_pays = True\n",
        );
        let t = translate_s3cfg(&m);
        assert_eq!(t.proxy.as_deref(), Some("http://proxy.local:8080"));
        assert_eq!(t.region.as_deref(), Some("eu-west-1"));
        assert_eq!(t.retry_count, Some(3));
        assert_eq!(t.limitrate, Some(1_048_576));
        assert_eq!(t.request_payer.as_deref(), Some("requester"));
    }

    #[test]
    fn parse_byte_rate_accepts_plain_and_suffixed() {
        assert_eq!(parse_byte_rate("1048576").unwrap(), 1_048_576);
        assert_eq!(parse_byte_rate("1MiB").unwrap(), 1_048_576);
        assert_eq!(parse_byte_rate("1MB").unwrap(), 1_000_000);
        assert!(parse_byte_rate("bogus").is_err());
    }

    #[test]
    fn rs5cmd_ini_round_trips() {
        let t = Translated {
            endpoint_url: Some("https://rgw.osris.org".to_string()),
            addressing_style: Some("path".to_string()),
            region: Some("us-east-1".to_string()),
            no_verify_ssl: true,
            limitrate: Some(2_000_000),
            request_payer: Some("requester".to_string()),
            // Secrets must NOT be serialized.
            access_key: Some("AK".to_string()),
            secret_key: Some("SK".to_string()),
            ..Default::default()
        };
        let ini = t.to_rs5cmd_ini();
        assert!(
            !ini.contains("AK") && !ini.contains("SK"),
            "secrets leaked into ~/.rs5cmd"
        );
        let back = from_rs5cmd(&parse_ini(&ini));
        assert_eq!(back.endpoint_url, t.endpoint_url);
        assert_eq!(back.addressing_style, t.addressing_style);
        assert_eq!(back.region, t.region);
        assert!(back.no_verify_ssl);
        assert_eq!(back.limitrate, t.limitrate);
        assert_eq!(back.request_payer, t.request_payer);
    }
}
